### PR TITLE
Use real repos

### PR DESCRIPTION
**Pull request by nickelsen**
This will be updated before merge with refs to master-branches when related PRs are merged in sc2reader, ggpyjobs, esdb and ggtracker components.

### CODE REVIEW

**Comment by dsjoerg** [comment]
Hi @nickelsen I believe this is ready to go, as I have taken in all the relevant code.

**Comment by nickelsen** [comment]
Yes, this it ready to go - I have updated it to point to official repos everywhere!

**Comment by dsjoerg** [comment]
I burned >half an hour last night trying to figure out how to update submodule references in my own checkout.  I found so many conflicting pieces of advice about how to do, I even stooped to reading man pages, nothing worked.

https://git-scm.com/docs/git-submodule
http://stackoverflow.com/questions/14404704/how-do-i-replace-a-git-submodule-with-another-repo
http://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error

The struggle is real

**Comment by nickelsen** [comment]
I know - it's crazy trying to wrap ones mind around submodules, branches and multiple remotes. I never worked with submodules before and this has blown my mind several times on so many levels.

But everything considered, I think it's pretty good now and I've at least learned something along the way. Ideally we'd set up something that monitors the master branch of the four repos in the stack and pushes an update of the references in this repo whenever they change. I'll have a look if we can get something free for open source somewhere.

**Pull request merged**
